In [1]:
pip install kaggle

Requirement already satisfied: kaggle in c:\users\adminr\anaconda3\lib\site-packages (1.6.17)
Requirement already satisfied: six>=1.10 in c:\users\adminr\anaconda3\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in c:\users\adminr\anaconda3\lib\site-packages (from kaggle) (2024.8.30)
Requirement already satisfied: python-dateutil in c:\users\adminr\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: requests in c:\users\adminr\anaconda3\lib\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in c:\users\adminr\anaconda3\lib\site-packages (from kaggle) (4.66.5)
Requirement already satisfied: python-slugify in c:\users\adminr\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: urllib3 in c:\users\adminr\anaconda3\lib\site-packages (from kaggle) (2.2.3)
Requirement already satisfied: bleach in c:\users\adminr\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: packaging in c:\users\adminr\anaconda3\lib\site-packages (from bleach->kaggle) (24.1)
Requirement already satisfied: webencodings in c:\users\adminr\anaconda3\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\adminr\anaconda3\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\adminr\anaconda3\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\adminr\anaconda3\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: colorama in c:\users\adminr\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import os
import kaggle

In [7]:
!kaggle datasets download ankitbansal06/retail-orders -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
Downloading orders.csv.zip to C:\Users\adminR

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 214kB/s]
100%|##########| 200k/200k [00:00<00:00, 214kB/s]

In [11]:
import zipfile

In [15]:
with zipfile.ZipFile(r"C:\Users\adminR\orders.csv.zip",'r')as raw_file:
    raw_file.extractall(r"C:\Users\adminR")
    print(f'Files have been extracted to : {r"C:\Users\adminR"}')
    print("Sucessfully unziped the file.")

Files have been extracted to : C:\Users\adminR
Sucessfully unziped the file.

In [3]:
import pandas as pd

In [21]:
df = pd.read_csv(r"C:\Users\adminR\orders.csv")
df

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [27]:
df.isnull().sum()

Order Id            0
Order Date          0
Ship Mode           0
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [25]:
df.dropna(inplace=True)

In [33]:
df = df.rename(columns = {'Order Id':'order_id',
             'Order Date':'order_date',
             'Ship Mode':'ship_mode',
             'Segment':'segment',
             'Country':'country',
'City':'city',
'State':'state',
'Postal Code':'postal_code',
'Region	Category':'region_category',
'Sub Category':'sub_category',
'Product Id':'product_id',
'cost price':'cost_price',
'List Price':'list_price',
'Quantity':'quantity',
'Discount Percent':'discount_percent'})

In [35]:
df.columns.str.strip()
print(df.columns)

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'Region', 'Category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [39]:
df['discount_price'] = df['list_price'] * df['discount_percent'] / 100
df['sales_price'] = df['list_price'] - df['discount_price']
df['profit'] = df['sales_price'] - df['cost_price']

In [41]:
print(df.columns)

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'Region', 'Category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent', 'discount_price', 'sales_price', 'profit'],
      dtype='object')

In [47]:
df=df.to_csv(r"C:\Users\adminR\retail_order.csv")

In [15]:
df= pd.read_csv(r"C:\Users\adminR\retail_order.csv")
df

,Unnamed: 0,order_id,order_date,ship_mode,segment,country,city,state,postal_code,Region,Category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount_price,sales_price,profit
0,0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9988,9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8,-1.2
9989,9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4,16.4
9990,9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8,34.8
9991,9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1,-0.9
9992,9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8,22.8

In [1]:
pip install mysql-connector-python pandas sqlalchemy

Requirement already satisfied: mysql-connector-python in c:\users\adminr\anaconda3\lib\site-packages (9.1.0)
Requirement already satisfied: pandas in c:\users\adminr\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: sqlalchemy in c:\users\adminr\anaconda3\lib\site-packages (2.0.36)
Requirement already satisfied: numpy>=1.26.0 in c:\users\adminr\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\adminr\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\adminr\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\adminr\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\adminr\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\adminr\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: six>=1.5 in c:\users\adminr\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import mysql.connector
from sqlalchemy import create_engine

In [7]:
connector = mysql.connector.connect(
    host = "localhost",
    user = "root",
    password = "nbhuvanesh385"
)

In [7]:
cursor=connector.cursor()
cursor.execute("CREATE DATABASE IF NOT EXISTS retail_order")

In [17]:
engine = create_engine(f"mysql+mysqlconnector://root:nbhuvanesh385@localhost/retail_order")
table_name = "retail_orders"
df.to_sql(table_name, con=engine, index=False, if_exists='replace')
print("CSV data has been successfully imported into MySQL.")

CSV data has been successfully imported into MySQL.

In [9]:
import psycopg2
conn = psycopg2.connect(
    host="localhost",
    database="retail_order",
    user="root",
    password="nbhuvanesh385"
)

try:
    with conn.cursor() as cur:
        cur.execute("SELECT * orders;")
        rows = cur.fetchall()
        for row in rows:
            print(row)
except (Exception, psycopg2.Error) as error:
    print("Error while fetching data from PostgreSQL", error)
finally:
    if conn:
        conn.close()
        print("PostgreSQL connection is closed")

ModuleNotFoundError: No module named 'psycopg2'